# Use an official fedora 32 image
FROM registry.fedoraproject.org/fedora:32

#setup pip
RUN yum update -y \
    && yum install -y python3 python3-libs python3-devel python3-pip


#pipenv installation
RUN pip3 install pipenv

WORKDIR /api

COPY . /api

#install project dependencies
RUN pipenv install

#CMD ["pipenv run python3 api/job-fetch-cronjob/fetch.py"]