# Use an official fedora 32 image
FROM registry.fedoraproject.org/fedora:32

ENV LANG=en_US.UTF-8

#setup pip
RUN yum update -y \
    && yum install -y python3 python3-libs python3-devel python3-pip


#pipenv installation
RUN pip install pipenv

WORKDIR /job-fetch-cronjob

COPY . /job-fetch-cronjob

#install project dependencies
RUN pipenv install --deploy

CMD ["pipenv", "run", "python", "async_job/job-fetch-cronjob/fetch.py"]


